### ISSUE TITLE
Redirect learn.adicu.com to Environment Setup

### ISSUE THREAD

**Issue by mjp2220** [adicu/adicu.github.com#287] opened 2015-01-31 00:38 UTC
@danrschlosser get on this. Link is currently http://old.adicu.com/Devfest-Environment-Setup/

**Comment by natebrennand** [comment] 2015-01-31 01:20
closing as dupe of https://github.com/adicu/learn-webdev/issues/36

**Closed by natebrennand** 2015-01-31 01:20 UTC
